from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

PROJECT_ROOT = Path(__file__).resolve().parents[1]
SRC_PATH = PROJECT_ROOT / "src"
if SRC_PATH.exists() and str(SRC_PATH) not in sys.path:
    sys.path.insert(0, str(SRC_PATH))

from peptide_flywheel.batch_artifacts import (
    ArtifactBatchManifest,
    build_batch_report_text,
    collect_batch_from_sources,
    write_batch_bundle,
)
from peptide_flywheel.validation import known_artifact_kinds


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Import/export a batch of artifacts and generate a quality report."
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    import_parser = subparsers.add_parser("import", help="Validate and normalise artifact batches.")
    import_parser.add_argument(
        "paths",
        nargs="+",
        help="Files or directories to import.",
    )
    import_parser.add_argument(
        "--kind",
        default="auto",
        choices=["auto"] + known_artifact_kinds(),
        help="Optional artifact kind hint for homogeneous inputs.",
    )
    import_parser.add_argument("--recursive", action="store_true", help="Recurse into subdirectories.")
    import_parser.add_argument("--lenient", action="store_true", help="Keep invalid rows and continue.")
    import_parser.add_argument(
        "--output-dir",
        default="data/phase2/batch_import",
        help="Directory for import manifest and normalized exports.",
    )

    export_parser = subparsers.add_parser("export", help="Export a manifest back to files.")
    export_parser.add_argument(
        "--manifest",
        required=True,
        help="Path to batch_manifest.json generated by the import command.",
    )
    export_parser.add_argument(
        "--output-dir",
        default="data/phase2/batch_export",
        help="Output directory for export files.",
    )
    export_parser.add_argument(
        "--artifact-kind",
        default=None,
        choices=known_artifact_kinds(),
        help="Optional filter by artifact kind.",
    )

    report_parser = subparsers.add_parser("report", help="Generate markdown report from manifest.")
    report_parser.add_argument("--manifest", required=True, help="Path to batch_manifest.json.")
    report_parser.add_argument(
        "--output-dir",
        default="data/phase2/batch_report",
        help="Directory for report output.",
    )
    return parser.parse_args()


def _load_manifest(path: Path) -> ArtifactBatchManifest:
    payload = json.loads(path.read_text(encoding="utf-8"))
    return ArtifactBatchManifest(
        generated_at=payload.get("generated_at", ""),
        source_paths=payload.get("source_paths", []),
        strict=bool(payload.get("strict", False)),
        recursive=bool(payload.get("recursive", False)),
        valid=payload.get("valid", []),
        invalid=payload.get("invalid", []),
    )


def _run_import(args: argparse.Namespace) -> None:
    strict = not args.lenient
    artifacts, failures, manifest = collect_batch_from_sources(
        source_paths=[Path(path) for path in args.paths],
        artifact_kind=None if args.kind == "auto" else args.kind,
        recursive=args.recursive,
        strict=strict,
    )
    output = write_batch_bundle(output_dir=Path(args.output_dir), manifest=manifest)
    print(f"Import complete: {manifest.valid_count} valid, {manifest.invalid_count} invalid")
    print(f"Manifest: {output['manifest']}")
    print(f"Bundle: {output['bundle']}")
    print(f"Report: {output['report']}")
    if failures and not strict:
        print("Warnings:")
        for failure in failures:
            print(f"- {failure.source}: {failure.message}")


def _run_export(args: argparse.Namespace) -> None:
    manifest = _load_manifest(Path(args.manifest))
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    count = 0
    for item in manifest.valid:
        if args.artifact_kind and item.get("artifact_type") != args.artifact_kind:
            continue
        kind = item.get("artifact_type") or "unknown"
        artifact_id = item.get("artifact_id") or "unknown"
        target_dir = output_dir / kind
        target_dir.mkdir(parents=True, exist_ok=True)
        destination = target_dir / f"{artifact_id}.json"
        destination.write_text(json.dumps(item.get("payload", {}), indent=2), encoding="utf-8")
        count += 1

    report_path = output_dir / "batch_export_report.md"
    report_path.write_text(
        "# Batch export\n\n"
        + f"Exported {count} valid artifact(s).\n",
        encoding="utf-8",
    )
    print(f"Exported {count} artifacts to {output_dir}")
    print(f"Export report: {report_path}")


def _run_report(args: argparse.Namespace) -> None:
    manifest = _load_manifest(Path(args.manifest))
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    report_path = output_dir / "batch_report.md"
    report_path.write_text(build_batch_report_text(manifest), encoding="utf-8")
    print(f"Report generated: {report_path}")


def main() -> None:
    args = _parse_args()
    if args.command == "import":
        _run_import(args)
    elif args.command == "export":
        _run_export(args)
    elif args.command == "report":
        _run_report(args)


if __name__ == "__main__":
    try:
        main()
    except (ValueError, KeyError, FileNotFoundError) as exc:
        print(f"Batch command failed: {exc}")
        raise SystemExit(1)
